// src/data.js
export const products = [
  {
    id: 7,
    name: 'Çilçıraqlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Otaq işıqları',
    category: 'İşıqlandırma',
    image: 'src/assets/cilciraq.jpg',
    fullName:'ÇİLÇIRAQ 9638-6'
  },
  {
    id: 8,
    name: 'Masa lampaları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Otaq işıqları',
    category: 'İşıqlandırma',
    image: 'src/assets/masalampasi.jpg',
    hundurluk: '5cm',
    uzunluq:'20cm',
    fullName:'STOLÜSTÜ LAMPA TY-2018-WH'
  },
  {
    id: 9,
    name: 'Plafonlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Otaq işıqları',
    category: 'İşıqlandırma',
    image: 'src/assets/plafonlar.jpg',
  },
  {
    id: 10,
    name: 'Torşerlər',
    model: '2021',
    year: '2021',
    price: 20,
    category: 'İşıqlandırma',
    catname: 'Otaq işıqları',
    image: 'src/assets/avtomat.jpg',
    cereyansiddeti:'5 watt'
  },
  {
    id: 11,
    name: 'Bralar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Otaq işıqları',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 12,
    name: 'Gizli işıqlar və aksesuarları',
    model: '2021',
    year: '2021',
    price: 20,
    category: 'İşıqlandırma',
    catname: 'Otaq işıqları',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 13,
    name: 'Led lampalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Lampalar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 14,
    name: 'Eko (spiral) lampalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Lampalar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 15,
    name: 'Hallogen lampalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Lampalar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 16,
    name: 'Lüminesent lampalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Lampalar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 17,
    name: 'Vitrin spot və projektor lampaları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Lampalar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },

  // Category: Spotlar
  {
    id: 18,
    name: 'Fasad spotları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Spotlar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 19,
    name: 'Led spotlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Spotlar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 20,
    name: 'Sadə spotlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Spotlar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 21,
    name: 'Spot rayları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Spotlar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 22,
    name: 'Vitrin spotları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Spotlar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 23,
    name: 'İşıqlandırma panelləri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Spotlar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 24,
    name: 'Drayverlər, adaptorlar, pultlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Spotlar',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },

  // Category: Küçə işıqları
  {
    id: 25,
    name: 'Dirək işıqları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Küçə işıqları',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 26,
    name: 'Divar işıqları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Küçə işıqları',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 27,
    name: 'Fənərlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Küçə işıqları',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 28,
    name: 'Projektorlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Küçə işıqları',
    category: 'İşıqlandırma',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 29,
    name: 'Aulmo',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Razetka vklyuçatel',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 30,
    name: 'Günsan',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Razetka vklyuçatel',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 31,
    name: 'Mirsa',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Razetka vklyuçatel',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 32,
    name: 'Tomas',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Razetka vklyuçatel',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },

  // Category: Naqillər, kabellər
  {
    id: 33,
    name: 'Antena kabelləri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 34,
    name: 'Elektrik izolyasiya boruları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 35,
    name: 'Elektrik kabelləri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 36,
    name: 'İnternet və təhlükəsizlik kabelləri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 37,
    name: 'Kabel dartanlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 38,
    name: 'Kabel kanalları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 39,
    name: 'Skoplar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 40,
    name: 'Telefon kabelləri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 41,
    name: 'Ucluqlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 42,
    name: 'Uzadıcılar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Naqillər, kabellər',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },

  // Category: Elektrik aksesuarları
  {
    id: 43,
    name: 'Avtomat darağı, planka, torpaqlama çubuğu',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik aksesuarları',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 44,
    name: 'Kembriklər, izolentlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik aksesuarları',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 45,
    name: 'Patronlar, çəngəllər(vilkalar), keçidlər(perexodniklər)',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik aksesuarları',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 46,
    name: 'Sensorlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik aksesuarları',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 47,
    name: 'Xamıtlar, zajimlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik aksesuarları',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },

  // Category: Elektrik qutuları
  {
    id: 48,
    name: 'Germetik qutular',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik qutuları',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 49,
    name: 'Montaj qutuları (Karobkalar)',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik qutuları',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },

  // Category: Elektrik tənzimləyiciləri
  {
    id: 50,
    name: 'Generatorlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik tənzimləyiciləri',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 51,
    name: 'Stablizatorlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik tənzimləyiciləri',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 52,
    name: 'Transformatorlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrik tənzimləyiciləri',
    category: 'Elektrik',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 54,
    name: 'Drellər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Drel, laqonda və perforatorlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 55,
    name: 'Ehtiyat hissələr',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Drel, laqonda və perforatorlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 56,
    name: 'Hava nasosu',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Drel, laqonda və perforatorlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 57,
    name: 'Kompressorlar və aksesuarları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Drel, laqonda və perforatorlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 58,
    name: 'Laqondalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Drel, laqonda və perforatorlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 59,
    name: 'Mikserlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Drel, laqonda və perforatorlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 60,
    name: 'Perforatorlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Drel, laqonda və perforatorlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 62,
    name: 'Çarx makinaları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrikli mişarlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 63,
    name: 'Elektrikli şkurka aparatı',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrikli mişarlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 64,
    name: 'Frez və bıçaqları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrikli mişarlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 65,
    name: 'Lobziklər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrikli mişarlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 66,
    name: 'Mişar və tiyələri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrikli mişarlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 67,
    name: 'Rəndələr',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Elektrikli mişarlar',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 69,
    name: 'Aksesuarlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qaynaq vasitələri',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 70,
    name: 'Lehimləmə aləti',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qaynaq vasitələri',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 71,
    name: 'PVC qaynaq ütüləri və başlıqları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qaynaq vasitələri',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 72,
    name: 'Qaynaq aparatları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qaynaq vasitələri',
    category: 'Elektrikli əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 73,
    name: 'Beton və daş üçün sverlolar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Sverlolar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 74,
    name: 'Meçiklər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Sverlolar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 75,
    name: 'Metal üçün sverlolar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Sverlolar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 76,
    name: 'Mərmər üçün sverlolar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Sverlolar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 77,
    name: 'Stəkan sverlolar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Sverlolar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 78,
    name: 'Şüşə üçün sverlolar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Sverlolar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 79,
    name: 'Taxta üçün sverlolar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Sverlolar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 80,
    name: 'Metrə, xətkeş',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Ölçü alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 81,
    name: 'Monometrlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Ölçü alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 82,
    name: 'Ştangerlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Ölçü alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 83,
    name: 'Su tərəzisi, urivinlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Ölçü alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 84,
    name: 'Termometrlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Ölçü alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 85,
    name: 'Tərəzilər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Ölçü alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 86,
    name: 'Usta qələmləri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Ölçü alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 87,
    name: 'Bantlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Skoç və bantlar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 88,
    name: 'İkitərəfli skoçlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Skoç və bantlar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 89,
    name: 'Kağız skoçlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Skoç və bantlar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 90,
    name: 'Polietilen skoçlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Skoç və bantlar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 91,
    name: 'Salafanlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Skoç və bantlar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 92,
    name: 'Sərhəd lenti',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Skoç və bantlar',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 93,
    name: 'Asma qıfıllar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qapı və pəncərə materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 94,
    name: 'Petlələr',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qapı və pəncərə materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 95,
    name: 'Pəncərə toru və bantlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qapı və pəncərə materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 96,
    name: 'Qapı kilidləri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qapı və pəncərə materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 97,
    name: 'Qapı qolları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qapı və pəncərə materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 98,
    name: 'Qapı-Pəncərə aksesuarları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Qapı və pəncərə materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 99,
    name: 'Ayaqqabılar, çəkmələr',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'İş təhlükəsizliyi və geyim',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 100,
    name: 'Əlcəklər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'İş təhlükəsizliyi və geyim',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 101,
    name: 'İşçi geyimləri',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'İş təhlükəsizliyi və geyim',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 102,
    name: 'Kaskalar, eynəklər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'İş təhlükəsizliyi və geyim',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 103,
    name: 'Maskalar, burunluqlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'İş təhlükəsizliyi və geyim',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 104,
    name: 'Usta çantaları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'İş təhlükəsizliyi və geyim',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 105,
    name: 'Anker boltlar, yivli asılqanlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Xırdavat materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 106,
    name: 'Mismarlar, dubellər və skoplar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Xırdavat materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 107,
    name: 'Probkalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Xırdavat materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 108,
    name: 'Şuruplar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Xırdavat materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 109,
    name: 'Zaklyovka',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Xırdavat materialları',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 110,
    name: 'Açarlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 111,
    name: 'Bıçaqlar, rezaklar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 112,
    name: 'Burğaclar (Atvyorkalar)',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 113,
    name: 'Çəkic, balta, kəsər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 114,
    name: 'Əl nasosu',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 115,
    name: 'İsgənələr, zubillər, baradoklar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 116,
    name: 'Kafelkəsənlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 117,
    name: 'Lerkalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 118,
    name: 'Məngənələr, şüşətutanlar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 119,
    name: 'Mikserlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 120,
    name: 'Mişarlar, qayçılar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 121,
    name: 'Mıxçəkənlər, linglər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 122,
    name: 'Plastqubtsalar, kəlbətinlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 123,
    name: 'Rəndələr',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 124,
    name: 'Skop və mismar tapançaları',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Mexaniki əl alətləri',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 125,
    name: 'Daş, beton üçün disklər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 126,
    name: 'Fırçalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 127,
    name: 'Keramika üçün disklər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 128,
    name: 'Metal üçün disklər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 129,
    name: 'Nasadkalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 130,
    name: 'Şkurkalar',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 131,
    name: 'Şüşə kəsənlər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 132,
    name: 'Taxta üçün disklər',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },
  {
    id: 133,
    name: 'Yeyələr',
    model: '2021',
    year: '2021',
    price: 20,
    catname: 'Kəsici və yonucu vasitələr',
    category: 'Xırdavat və əl alətləri',
    image: 'src/assets/avtomat.jpg',
  },

  
    {
        id: 134,
        name: 'Duman sensorları',
        model: 'Model A',
        year: '2022',
        price: 50,
        catname: 'Yanğın Aşkar Etmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/duman_sensoru.jpg', // uygun resim yolu
    },
    {
        id: 135,
        name: 'İstilik sensorları',
        model: 'Model B',
        year: '2022',
        price: 60,
        catname: 'Yanğın Aşkar Etmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/istilik_sensoru.jpg', // uygun resim yolu
    },
    {
        id: 136,
        name: 'Yanğın alarm panelləri',
        model: 'Model C',
        year: '2022',
        price: 120,
        catname: 'Yanğın Aşkar Etmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/yangin_alarm_paneli.jpg', // uygun resim yolu
    },
    {
        id: 137,
        name: 'Sprinkler sistemləri',
        model: 'Model D',
        year: '2022',
        price: 150,
        catname: 'Yanğın Söndürmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/sprinkler_sistemi.jpg', // uygun resim yolu
    },
    {
        id: 138,
        name: 'Quru kimyəvi toz aparatları',
        model: 'Model E',
        year: '2022',
        price: 200,
        catname: 'Yanğın Söndürmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/quru_kimyavi_toz_aparati.jpg', // uygun resim yolu
    },
    {
        id: 139,
        name: 'Karbon dioksid (CO2) söndürmə sistemləri',
        model: 'Model F',
        year: '2022',
        price: 250,
        catname: 'Yanğın Söndürmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/co2_sondurma_sistemi.jpg', // uygun resim yolu
    },
    {
        id: 140,
        name: 'Yanğın söndürmə balonları',
        model: 'Model G',
        year: '2022',
        price: 80,
        catname: 'Yanğın Təhlükəsizliyi Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/yangin_sondurme_balonlari.jpg', // uygun resim yolu
    },
    {
        id: 141,
        name: 'Yardımçı avadanlıqlar (şlanq, nozzle və s.)',
        model: 'Model H',
        year: '2022',
        price: 30,
        catname: 'Yanğın Təhlükəsizliyi Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/yardimci_avadanliqlar.jpg', // uygun resim yolu
    },
    {
        id: 142,
        name: 'Evakuasiya işıqları',
        model: 'Model I',
        year: '2022',
        price: 70,
        catname: 'Evakuasiya Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/evakuasiya_isiklari.jpg', // uygun resim yolu
    },
    {
        id: 143,
        name: 'Səsli xəbərdarlıq sistemləri',
        model: 'Model J',
        year: '2022',
        price: 90,
        catname: 'Evakuasiya Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/sesli_xeberdarliq.jpg', // uygun resim yolu
    },
    {
        id: 144,
        name: 'Fövqəladə çıxış istiqamətləri üçün işarələr',
        model: 'Model K',
        year: '2022',
        price: 40,
        catname: 'Evakuasiya Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/foq_xeberdarliq_isareleri.jpg', // uygun resim yolu
    },
    {
        id: 145,
        name: 'Mərkəzi nəzarət sistemləri',
        model: 'Model L',
        year: '2022',
        price: 300,
        catname: 'Yanğın İdarəetmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/merkezi_nezaret_sistemi.jpg', // uygun resim yolu
    },
    {
        id: 146,
        name: 'Monitorinq və məlumat sistemləri',
        model: 'Model M',
        year: '2022',
        price: 350,
        catname: 'Yanğın İdarəetmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/monitorinq_sistemi.jpg', // uygun resim yolu
    },
    {
        id: 147,
        name: 'Uzaqdan nəzarət cihazları',
        model: 'Model N',
        year: '2022',
        price: 400,
        catname: 'Yanğın İdarəetmə Avadanlıqları',
        category: 'Yanğın sistemləri',
        image: 'src/assets/uzaktan_nezaret.jpg', // uygun resim yolu
    },
    {
        id: 148,
        name: 'Daxili kameralar',
        model: 'Model O',
        year: '2022',
        price: 100,
        catname: 'Kamera Sistemləri',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/daxili_kamera.jpg', // uygun resim yolu
    },
    {
        id: 149,
        name: 'Xarici kameralar',
        model: 'Model P',
        year: '2022',
        price: 120,
        catname: 'Kamera Sistemləri',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/xarici_kamera.jpg', // uygun resim yolu
    },
    {
        id: 150,
        name: 'PTZ (Pan-Tilt-Zoom) kameralar',
        model: 'Model Q',
        year: '2022',
        price: 150,
        catname: 'Kamera Sistemləri',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/ptz_kamera.jpg', // uygun resim yolu
    },
    {
        id: 151,
        name: 'İP kameralar',
        model: 'Model R',
        year: '2022',
        price: 130,
        catname: 'Kamera Sistemləri',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/ip_kamera.jpg', // uygun resim yolu
    },
    {
        id: 152,
        name: 'Analoq kameralar',
        model: 'Model S',
        year: '2022',
        price: 90,
        catname: 'Kamera Sistemləri',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/analoq_kamera.jpg', // uygun resim yolu
    },
    {
        id: 153,
        name: 'Müşahidə monitorları',
        model: 'Model T',
        year: '2022',
        price: 250,
        catname: 'Monitorinq Avadanlıqları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/musahid_monitor.jpg', // uygun resim yolu
    },
    {
        id: 154,
        name: 'Video idarəetmə sistemləri',
        model: 'Model U',
        year: '2022',
        price: 300,
        catname: 'Monitorinq Avadanlıqları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/video_idareetme.jpg', // uygun resim yolu
    },
    {
        id: 155,
        name: 'Ekranlar üçün video qeyd cihazları (DVR/NVR)',
        model: 'Model V',
        year: '2022',
        price: 400,
        catname: 'Monitorinq Avadanlıqları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/video_qeyd_cihazi.jpg', // uygun resim yolu
    },
    {
        id: 156,
        name: 'Hərəkət sensorları',
        model: 'Model W',
        year: '2022',
        price: 80,
        catname: 'Alarm və Hərəkət Sensorları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/hereket_sensoru.jpg', // uygun resim yolu
    },
    {
        id: 157,
        name: 'Açıq-qapalı sensorlar',
        model: 'Model X',
        year: '2022',
        price: 70,
        catname: 'Alarm və Hərəkət Sensorları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/aciq_qapali_sensor.jpg', // uygun resim yolu
    },
    {
        id: 158,
        name: 'Səs sensorları',
        model: 'Model Y',
        year: '2022',
        price: 60,
        catname: 'Alarm və Hərəkət Sensorları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/ses_sensoru.jpg', // uygun resim yolu
    },
    {
        id: 159,
        name: 'Mərkəzi idarəetmə panelləri',
        model: 'Model Z',
        year: '2022',
        price: 300,
        catname: 'İdarəetmə və Qeyd Sistemləri',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/merkezi_idareetme.jpg', // uygun resim yolu
    },
    {
        id: 160,
        name: 'Mobil tətbiqlərlə idarəetmə',
        model: 'Model AA',
        year: '2022',
        price: 200,
        catname: 'İdarəetmə və Qeyd Sistemləri',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/mobil_tetbiq.jpg', // uygun resim yolu
    },
    {
        id: 161,
        name: 'Bulud əsaslı qeyd sistemləri',
        model: 'Model AB',
        year: '2022',
        price: 350,
        catname: 'İdarəetmə və Qeyd Sistemləri',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/bulud_qeyd_sistemi.jpg', // uygun resim yolu
    },
    {
        id: 162,
        name: 'Kamera montaj aksesuarları',
        model: 'Model AC',
        year: '2022',
        price: 40,
        catname: 'Aksesuarlar və Dəstək Avadanlıqları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/kamera_montaj.jpg', // uygun resim yolu
    },
    {
        id: 163,
        name: 'İşıqlandırma sistemləri',
        model: 'Model AD',
        year: '2022',
        price: 80,
        catname: 'Aksesuarlar və Dəstək Avadanlıqları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/isiklandirma.jpg', // uygun resim yolu
    },
    {
        id: 164,
        name: 'Kabellər və qoşma cihazları',
        model: 'Model AE',
        year: '2022',
        price: 30,
        catname: 'Aksesuarlar və Dəstək Avadanlıqları',
        category: 'Kamera və təhlükəsizlik sistemləri',
        image: 'src/assets/kabellar.jpg', // uygun resim yolu
    },




  
//-------------------------------------
  

//-------------------------------------























  
  

];
